[project]
name = "free-lunch-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tsung_macbook", email = "tctsung@nyu.edu" }
]
requires-python = ">=3.7"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
